# Generated by Django 4.1.7 on 2023-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("city_name", models.CharField(max_length=255)),
                ("state_name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("temp", models.FloatField()),
                ("temp_min", models.FloatField()),
                ("temp_max", models.FloatField()),
                ("humidity", models.FloatField()),
                ("rain", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Hourly",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("city_name", models.CharField(max_length=255)),
                ("state_name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("temp", models.FloatField()),
                ("humidity", models.FloatField()),
                ("rain", models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="hourly",
            constraint=models.UniqueConstraint(
                fields=("city_name", "date"), name="city_date_hourly"
            ),
        ),
        migrations.AddConstraint(
            model_name="daily",
            constraint=models.UniqueConstraint(
                fields=("city_name", "date"), name="city_date_daily"
            ),
        ),
    ]
