# Generated by Django 4.1.7 on 2023-02-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hourly",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
